### ISSUE TITLE
does not work when powerline-daemon is used

### ISSUE THREAD

**Issue by tchize** [justinludwig/powerline-svnstatus#1]
the svn command are run on the current folder of the daemon, not the current folder of the shell

```
    proc = Popen(['svn', 'info'], stdout=PIPE, stderr=PIPE)
```

You correctly check there is a cwd in the segment info, but don't use it. Solution: use it

```
    proc = Popen(['svn', 'info', cwd], stdout=PIPE, stderr=PIPE)
```

same apply for svn status

**Comment by justinludwig** [comment]
Thanks for filing this issue -- I made the change you suggested.
