### ISSUE TITLE
breaks when using svn-external

### ISSUE THREAD

**Issue by tchize** [justinludwig/powerline-svnstatus#2]
The code assume that each line of svn status will provide a file / folder status with one letter and it will try to classify it. If you are running with a svn external, the svn status looks like this

`?       .project
X       admin
M       automatix/java/com/acunia/automatix/server/eshipco/ESEngine.java
M       automatix/java/com/acunia/automatix/server/eshipco/EWAEngine.java
M       automatix/library.properties
?       automatix/resource/setup/server-devDavidD.properties
?       automatix/resource/setup/server-localhost.properties
A       automatix-eshipco
A  +    automatix-eshipco/build.xml
A  +    automatix-eshipco/library.properties

Performing status on external item at 'admin/build':
`
it's choking on last line. In build_status_segment, pair[0] is an empty string and pair[0][0] is sending an exception.

Quick fix: use --ignore-externals to get svn status
`proc = Popen(['svn', 'status', '--ignore-externals', cwd], stdout=PIPE, stderr=PIPE)`

and handle empty pairs as a safenet
`general_group = 'svnstatus_%s' % pair[0][0] if pair[0] else 'svnstatus_'
`

**Comment by justinludwig** [comment]
Thanks for filing this issue -- I made the changes you suggested, but I also ended up filtering out the blank line and `Performing status on externals...` line when parsing the status flags.
