### ISSUE TITLE
Non english language is not supported

### ISSUE THREAD

**Issue by tchize** [justinludwig/powerline-svnstatus#3]
First operation done during svn status parsing is looking for the string 'URL: '. But on french language, string is 'URL :', because french language mandate space before semicolumn and not after. On a french station, this plugin will just consider path as not an svn path. This could be widely different depending on other languages i suspect.

```
svn info
Chemin : .
Chemin racine de la copie de travail : /home/xxxx/Workspaces/coba/coba-root
URL : https://xxxx/svn-ptx/coba/trunk
Relative URL: ^/trunk
```

Solution, force SVN to run in "C" environment to fallback to classical english output:

```
def make_env(self, segment_info):
    myenv = segment_info["environ"].copy()
    myenv["LANG"]="C"
    myenv["LC_MESSAGES"]="C"
    return myenv


   proc = Popen(['svn', 'info'], stdout=PIPE, stderr=PIPE, env=self.make_env(segment_info))
   proc = Popen(['svn', 'status'], stdout=PIPE, stderr=PIPE, env=self.make_env(segment_info))
```

**Comment by justinludwig** [comment]
Thanks for filing this issue -- I made the change you suggested.
