### ISSUE TITLE
repository status marked as dirty if there are external references

### ISSUE THREAD

**Issue by tchize** [justinludwig/powerline-svnstatus#4]
script is assuming that if svn status returns something, the folder is dirty. However, if it returns only external references (marked X), it should not consider folder dirty:

```
dispatcher > workbench > war > copan/trunk > X 1 > LANG=C svn status
X       js

Performing status on external item at 'js':
dispatcher > workbench > war > copan/trunk > X 1 >
```

**Comment by justinludwig** [comment]
Thanks for filing these issues! I added an `is_dirty` check that avoids marking the repo as dirty if the only statuses are `S` or `X`. I also figured it might be useful to display the repo as dirty if any of the files in the external directories themselves had been modified (or had been flagged with some other dirty status) -- so I included externals in the status check, but skipped the blank line and `Performing status on external...` line when parsing the `svn status` output. Let me know if you have any other issues or suggestions for that.
